<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMZTTQlX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMZTTQlX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMZTTQlX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMZTTQlX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMZTTQlX\App_KernelDevDebugContainer([
    'container.build_hash' => 'MZTTQlX',
    'container.build_id' => '290dfc6d',
    'container.build_time' => 1579254730,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMZTTQlX');
